In [2]:
import pandas as pd
import numpy as np

input_file = "OASIS3_MR_json.csv"
output_file = "oasis3-1per.csv"

df = pd.read_csv(input_file)
df

,subject_id,label,acccession,release version,scan category,filename,Modality,MagneticFieldStrength,Manufacturer,ManufacturersModelName,...,PhaseOversampling,EchoNumber,Interpolation2D,RawImage,ConsistencyInfo,MultibandAccelerationFactor,PhaseEncodingAxis,AcquisitionDateTime,PhaseEncodingLines,AccelFactPE
0,OAS30044,OAS30044_MR_d0061,CENTRAL_E09340,2018 Release,fieldmap,sub-OAS30044_ses-d0061_echo-1_run-01_fieldmap....,MR,3.0,Siemens,Biograph_mMR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,OAS31435,OAS31435_MR_d0071,CENTRAL02_E02488,2022 Release,asl,sub-OAS31435_sess-d0071_asl.json,MR,3.0,Siemens,Biograph_mMR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,OAS31172,OAS31172_MR_d0407,CENTRAL_E11127,2018 Release,T2star,sub-OAS31172_ses-d0407_T2star.json,MR,3.0,Siemens,TrioTim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,OAS31430,OAS31430_MR_d0060,CENTRAL02_E02831,2022 Release,T2star,sub-OAS31430_sess-d0060_T2star.json,MR,3.0,Siemens,MAGNETOM_Vida,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,OAS30096,OAS30096_MR_d2948,CENTRAL02_E02487,2022 Release,T1w,sub-OAS30096_sess-d2948_T1w.json,MR,3.0,Siemens,Biograph_mMR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30334,OAS30492,OAS30492_MR_d0090,CENTRAL_E10047,2018 Release,asl,sub-OAS30492_ses-d0090_run-02_asl.json,MR,3.0,Siemens,TrioTim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30335,OAS30817,OAS30817_MR_d1254,CENTRAL_E10561,2018 Release,bold-rest,sub-OAS30817_ses-d1254_task-rest_run-02_bold.json,MR,3.0,Siemens,TrioTim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30336,OAS31149,OAS31149_MR_d0061,CENTRAL_E11086,2018 Release,fieldmap,sub-OAS31149_ses-d0061_echo-2_run-01_fieldmap....,MR,3.0,Siemens,Biograph_mMR,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30337,OAS30040,OAS30040_MR_d4230,CENTRAL_E09335,2018 Release,minIP,sub-OAS30040_ses-d4230_minIP.json,MR,3.0,Siemens,TrioTim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30338,OAS30990,OAS30990_MR_d0107,CENTRAL_E10827,2018 Release,T2w,sub-OAS30990_ses-d0107_acq-TSE_T2w.json,MR,3.0,Siemens,TrioTim,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
random_seed = 42
df_one = (df.groupby("subject_id", group_keys=False).apply(lambda x: x.sample(1, random_state=random_seed)))
df_one['label']

/var/folders/r0/yw0tqbvj7wb9mnhswg85vdn40000gn/T/ipykernel_26033/3811040127.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_one = (df.groupby("subject_id", group_keys=False).apply(lambda x: x.sample(1, random_state=random_seed)))

19251    OAS30001_MR_d0757
479      OAS30002_MR_d0653
28739    OAS30003_MR_d1631
67       OAS30004_MR_d2229
26110    OAS30005_MR_d1274
               ...
1415     OAS31470_MR_d0007
23896    OAS31471_MR_d0059
4681     OAS31472_MR_d0045
9261     OAS31473_MR_d0136
1431     OAS31474_MR_d0150
Name: label, Length: 1376, dtype: object

In [6]:
df_label = pd.DataFrame(df_one['label'])
df_label

                   label
19251  OAS30001_MR_d0757
479    OAS30002_MR_d0653
28739  OAS30003_MR_d1631
67     OAS30004_MR_d2229
26110  OAS30005_MR_d1274
...                  ...
1415   OAS31470_MR_d0007
23896  OAS31471_MR_d0059
4681   OAS31472_MR_d0045
9261   OAS31473_MR_d0136
1431   OAS31474_MR_d0150

[1376 rows x 1 columns]

In [7]:
df_label.to_csv(output_file, index=False)

print(f"Saved {len(df_one)} rows to {output_file}")

Saved 1376 rows to oasis3-1per.csv